module.exports = {
  nodetypes: [
    'user',
    'Group',
    'PermissionSet',
    'accessRole',
    'lifecycleRole',
    'groupMember',
    'assignment',
    'file',
    'requestor',
    'actor',
    'predecessor',
    'nodeThumbnail',
  ],
  properties: [
    {
      name: '_id',
      type: 'string',
      unique: true,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['relationship', 'node'],
    },
    {
      name: '_ref',
      type: 'string',
      unique: true,
      mandatory: false,
      generated: false,
      core: true,
      validFor: ['node'],
    },
    {
      name: '_state',
      type: 'state',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
    },
    {
      name: '_thumbnail',
      type: 'node',
      unique: false,
      mandatory: false,
      generated: false,
      core: true,
      relationship: 'nt_5d79e3adnkcd25615637df85e122bcac',
      validFor: ['node'],
    },
    {
      name: '_releasedOn',
      type: 'date',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
    },
    {
      name: '_version',
      type: 'string',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
      default: '1.0.0',
    },
    {
      name: '_versionedOn',
      type: 'date',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
    },
    {
      name: '_createdOn',
      type: 'date',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['relationship', 'node'],
    },
    {
      name: '_modifiedOn',
      type: 'date',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
    },
    {
      name: '_history',
      type: 'json',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
      default: '[]',
    },
    {
      name: '_promotions',
      type: 'json',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
    },
    {
      name: '_serialized',
      type: 'multiselect',
      unique: false,
      mandatory: false,
      generated: false,
      core: true,
      validFor: ['node'],
      default: [],
    },
    {
      name: '_createdBy',
      type: 'string',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['relationship', 'node'],
    },
    {
      name: '_createdByName',
      type: 'string',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['relationship', 'node'],
    },
    {
      name: '_sequence',
      type: 'string',
      unique: false,
      mandatory: false,
      generated: false,
      core: true,
      validFor: ['relationship'],
    },
    {
      name: '_isEffective',
      type: 'boolean',
      unique: false,
      mandatory: false,
      generated: false,
      core: true,
      validFor: ['relationship'],
      default: false,
    },
    {
      name: '_isLatest',
      type: 'boolean',
      unique: false,
      mandatory: false,
      generated: false,
      core: true,
      validFor: ['relationship'],
      default: true,
    },
    {
      name: '_effectiveOn',
      type: 'date',
      unique: false,
      mandatory: false,
      generated: false,
      core: true,
      validFor: ['relationship'],
    },
    {
      name: '_lockable',
      type: 'boolean',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
    },
    {
      name: '_lockState',
      type: 'boolean',
      unique: false,
      mandatory: false,
      generated: false,
      core: true,
      validFor: ['node'],
    },
    {
      name: '_lockedBy',
      type: 'string',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
    },
    {
      name: '_lockedByName',
      type: 'string',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
    },
    {
      name: '_lockedOn',
      type: 'date',
      unique: false,
      mandatory: false,
      generated: 'api',
      core: true,
      validFor: ['node'],
    },
  ],
  permissionSets: ['user', 'part'],
  groups: ['Administrator'],
};

// Notes:
// Core Properties can be type of node, ONLY if there exists a relationship between the 2 nodes (like _createdBy)
// and even if the relationship is not created in datamodel.
// We are hardcoding this relationship in the code!


/* OTHER RELATIONSHIP PROPERTIES THAT ARE HARDCODED IN THE SYSTEM
_role,
_handled,
_handledState,
_changeComment,
_sourceNode,
linkName
*/
